### ISSUE TITLE
Typo with axWidth

### ISSUE THREAD

**Issue by fourcolors** [lens-protocol/react-native-lens-ui-kit#4]
Working on an EthDenver thing and noticed this bug when I'm trying to compile react native. PR coming, right below. 

<img width="593" alt="Screenshot 2023-02-26 at 9 28 02 PM" src="https://user-images.githubusercontent.com/51751/221474364-0ac1b2fa-d7e2-4f0e-8854-77d53ba9de73.png">

**Comment by dabit3** [comment]
hey, thank you for this!
